export enum PaymentMethodActionsEnum {
  SET_PAYMENT_METHOD = 'SET_PAYMENT_METHOD',
  SET_PAYMENT_METHOD_SUCCESS = 'SET_PAYMENT_METHOD_SUCCESS',
  SET_PAYMENT_METHOD_FAIL = 'SET_PAYMENT_METHOD_FAIL',
}
