export enum PlaidTokenActionsEnum {
  GENERATE_TOKEN = 'GENRATE_TOKEN',
  GENERATE_TOKEN_SUCCESS = 'GENRATE_TOKEN_SUCCESS',
  GENERATE_TOKEN_FAIL = 'GENRATE_TOKEN_FAIL',
  EXCHANGE_TOKEN = 'EXCHANGE_TOKEN',
  EXCHANGE_TOKEN_SUCCESS = 'EXCHANGE_TOKEN_SUCCESS',
  EXCHANGE_TOKEN_FAIL = 'EXCHANGE_TOKEN_FAIL',
}
