export enum ResetPasswordActionsEnum {
  REQUIRE_NEW_PASSWORD = 'REQUIRE_NEW_PASSWORD',
  REQUIRE_NEW_PASSWORD_SUCCESS = 'REQUIRE_NEW_PASSWORD_SUCCESS',
  REQUIRE_NEW_PASSWORD_FAIL = 'REQUIRE_NEW_PASSWORD_FAIL',
  RESET_PASSWORD = 'RESET_PASSWORD',
  RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD _SUCCESS',
  RESET_PASSWORD_FAIL = 'RESET_PASSWORD _FAIL',
  CHECK_LINK = 'CHECK_LINK',
  CHECK_LINK_SUCCESS = 'CHECK_LINK_SUCCESS',
  CHECK_LINK_FAIL = 'CHECK_LINK_FAIL',
}
