export enum UserActionsEnum {
  GET_USER = 'GET_USER',
  GET_USER_SUCCESS = 'GET_USER_SUCCESS',
  GET_USER_FAIL = 'GET_USER_FAIL',
  UPDATE_DATA = 'UPDATE_DATA',
  UPDATE_DATA_SUCCESS = 'UPDATE_DATA_SUCCESS',
  UPDATE_DATA_FAIL = 'UPDATE_DATA_FAIL',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS',
  CHANGE_PASSWORD_FAIL = 'CHANGE_PASSWORD_FAIL',
}
